version: '3'
services:  
  orders-stg:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: orders-stg
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production